# Harmony Jekyll theme general configurations
# baseurl: /

# Site live URL
url: http://cathaines.com

excerpt_separator: "<!-- more -->"

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Cat Haines
  # description: Writings about code, community, and creativity.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
   Personal home page of Cat Haines. I blog about code, community, and creativity.
  basetheme: darken # pre defined thmes are darken, blue-water, redish.

  author: # Author details
    name: Cat Haines
    email: haines2m@gmail.com
    url: http://cathaines.com
    signature: <3 Cat ðŸ˜¸

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-74437010-1

  # Profile links, leave blank to ignore
  social:
    github: cat-haines
    twitter: _cathaines
    medium: cathaines
    # facebook:
    # gplus: +
    # dribble:
    # pinterest:

# Conversion / Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# Permalinks
permalink: /:year/:month/:title/

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - vendor

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
